apiVersion: batch/v1
kind: Job
metadata:
  generateName: entry-tests-
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: entrytests
        image: mcr.microsoft.com/azure-cli:latest
        command: [sh, -c]
        args: 
          - |
            echo "Running entry tests"
      restartPolicy: Never
  backoffLimit: 1