apiVersion: batch/v1
kind: Job
metadata:
  generateName: validate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: validatesignature
        image: mcr.microsoft.com/azure-cli:latest
        command: [sh, -c]
        args: 
          - |
            echosss "Validating signatures"
      restartPolicy: Never
  backoffLimit: 4